import tkinter 
label = tkinter.Label(text='Штир forever!!!', font=('Times','30'), fg='green', bg='white') 
label.master.overrideredirect(True) 
label.master.geometry("+250+250") 
label.master.lift() 
label.master.wm_attributes("-topmost", True) 
label.master.wm_attributes("-disabled", True) 
label.master.wm_attributes("-transparentcolor", "white")
label.pack() 
label.mainloop()